import express from 'express';
import pg from 'pg';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const { Pool } = pg;
const app = express();
app.disable('x-powered-by');
app.use(express.json({ limit: '32kb' }));
const PORT = Number(process.env.PORT || 10000);
const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error('DATABASE_URL is required.'); process.exit(1); }
const pool = new Pool({ connectionString: DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : undefined, max: 10, idleTimeoutMillis: 30000, connectionTimeoutMillis: 5000 });
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const QUESTIONS = JSON.parse(fs.readFileSync(path.join(__dirname, 'data/questions.json'), 'utf8'));
const QUESTION_MAP = new Map(QUESTIONS.map(q => [Number(q.id), q]));
const CATALOG = { p2:{price:150,kind:'category'},p3:{price:150,kind:'category'},p4:{price:220,kind:'category'},p5:{price:150,kind:'category'},p6:{price:220,kind:'category'},p7:{price:250,kind:'category'},p8:{price:220,kind:'category'},p9:{price:350,kind:'category'},p10:{price:350,kind:'category'},p11:{price:220,kind:'category'},p12:{price:350,kind:'category'},p13:{price:220,kind:'category'},life_1:{price:80,kind:'lives',value:1},life_3:{price:200,kind:'lives',value:3},life_5:{price:350,kind:'lives',value:5},time_5:{price:130,kind:'time',value:5},time_10:{price:260,kind:'time',value:10},time_20:{price:480,kind:'time',value:20} };
function json(res,data,status=200){return res.status(status).json(data)}
function playerId(req){const id=String(req.get('x-player-id')||'').trim();return id.length>=16&&id.length<=128?id:null}
function requirePlayer(req,res){const id=playerId(req);if(!id){json(res,{error:'invalid_player'},400);return null}return id}
function publicState(row){return {player_id:row.player_id,coins:Number(row.coins),lives:Number(row.lives),time_bonus_secs:Number(row.time_bonus_secs),best_score:Number(row.best_score),unlocked:row.unlocked}}
async function ensurePlayer(client,id){const now=Date.now();await client.query(`INSERT INTO players(player_id,created_at,updated_at) VALUES($1,$2,$2) ON CONFLICT(player_id) DO NOTHING`,[id,now]);const r=await client.query(`SELECT * FROM players WHERE player_id=$1`,[id]);return r.rows[0]}
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,X-Player-Id');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.get('/health',async(_req,res)=>{try{await pool.query('SELECT 1');return json(res,{status:'ok'})}catch{return json(res,{status:'degraded'},503)}});
app.get('/v1/state',async(req,res)=>{const id=requirePlayer(req,res);if(!id)return;const client=await pool.connect();try{return json(res,publicState(await ensurePlayer(client,id)))}catch{return json(res,{error:'server_error'},500)}finally{client.release()}});
app.post('/v1/round',async(req,res)=>{const id=requirePlayer(req,res);if(!id)return;const body=req.body||{};const category=String(body.category||'').slice(0,16);const stage=Math.max(1,Math.min(10,Number(body.stage||1)));const hardMode=Boolean(body.hardMode);const answers=Array.isArray(body.answers)?body.answers.slice(0,8):[];if(!category||answers.length===0)return json(res,{error:'invalid_round'},400);const client=await pool.connect();try{await client.query('BEGIN');const player=await ensurePlayer(client,id);const unlocked=String(player.unlocked||'p0|p1').split('|').filter(Boolean);if(!unlocked.includes(category)){await client.query('ROLLBACK');return json(res,{error:'category_locked'},403)}const runId=crypto.randomUUID();await client.query(`INSERT INTO runs(run_id,player_id,category,stage,hard_mode,created_at) VALUES($1,$2,$3,$4,$5,$6)`,[runId,id,category,stage,hardMode,Date.now()]);let correct=0,score=0;const seen=new Set();for(const a of answers){const qid=Number(a?.questionId);if(seen.has(qid))continue;seen.add(qid);const q=QUESTION_MAP.get(qid);if(!q||String(q.assetId)!==category){await client.query('ROLLBACK');return json(res,{error:'question_category_mismatch'},400)}const answerIndex=Number(a?.answerIndex);const elapsed=Math.max(0,Math.min(60000,Number(a?.elapsedMs||0)));const baseTime=hardMode?Math.max(8500,11000-(stage-1)*250):Math.max(14000,18000-(stage-1)*500);const maxTime=baseTime+Math.min(60,Number(player.time_bonus_secs||0))*1000;const ok=Number.isInteger(answerIndex)&&answerIndex>=0&&answerIndex===Number(q.correta)&&elapsed<=maxTime;if(ok){correct++;score+=hardMode?20:10}await client.query(`INSERT INTO answers(run_id,question_id,answer_index,elapsed_ms,correct,created_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(run_id,question_id) DO NOTHING`,[runId,qid,answerIndex,elapsed,ok,Date.now()])}const reward=correct*2;const newCoins=Math.min(999999,Number(player.coins)+reward);const newBest=Math.max(Number(player.best_score),score);await client.query(`UPDATE players SET coins=$1,best_score=$2,updated_at=$3 WHERE player_id=$4`,[newCoins,newBest,Date.now(),id]);await client.query(`UPDATE runs SET closed=TRUE WHERE run_id=$1`,[runId]);const latest=await client.query('SELECT * FROM players WHERE player_id=$1',[id]);await client.query('COMMIT');return json(res,{runId,score,correct,total:answers.length,coins:newCoins,coinsAwarded:reward,bestScore:newBest,lives:Number(latest.rows[0].lives),time_bonus_secs:Number(latest.rows[0].time_bonus_secs),unlocked:latest.rows[0].unlocked})}catch(e){await client.query('ROLLBACK').catch(()=>{});console.error(e);return json(res,{error:'server_error'},500)}finally{client.release()}});
app.post('/v1/life/consume',async(req,res)=>{const id=requirePlayer(req,res);if(!id)return;const client=await pool.connect();try{await client.query('BEGIN');const player=await ensurePlayer(client,id);if(Number(player.lives)<=0){await client.query('ROLLBACK');return json(res,{error:'no_extra_life',state:publicState(player)},409)}const r=await client.query(`UPDATE players SET lives=lives-1,updated_at=$1 WHERE player_id=$2 RETURNING *`,[Date.now(),id]);await client.query('COMMIT');return json(res,publicState(r.rows[0]))}catch{await client.query('ROLLBACK').catch(()=>{});return json(res,{error:'server_error'},500)}finally{client.release()}});
app.post('/v1/purchase',async(req,res)=>{const id=requirePlayer(req,res);if(!id)return;const item=CATALOG[String(req.body?.itemId||'')];if(!item)return json(res,{error:'invalid_item'},400);const client=await pool.connect();try{await client.query('BEGIN');const player=await ensurePlayer(client,id);let unlocked=String(player.unlocked||'p0|p1').split('|').filter(Boolean);if(item.kind==='category'&&unlocked.includes(String(req.body.itemId))){await client.query('COMMIT');return json(res,publicState(player))}if(Number(player.coins)<item.price){await client.query('ROLLBACK');return json(res,{error:'insufficient_coins',state:publicState(player)},409)}let coins=Number(player.coins)-item.price;let lives=Number(player.lives),time=Number(player.time_bonus_secs);if(item.kind==='lives')lives=Math.min(99,lives+item.value);if(item.kind==='time')time=Math.min(60,time+item.value);if(item.kind==='category')unlocked=[...new Set([...unlocked,String(req.body.itemId)])];const r=await client.query(`UPDATE players SET coins=$1,lives=$2,time_bonus_secs=$3,unlocked=$4,updated_at=$5 WHERE player_id=$6 RETURNING *`,[coins,lives,time,unlocked.join('|'),Date.now(),id]);await client.query('COMMIT');return json(res,publicState(r.rows[0]))}catch{await client.query('ROLLBACK').catch(()=>{});return json(res,{error:'server_error'},500)}finally{client.release()}});
app.use((_req,res)=>json(res,{error:'not_found'},404));
app.listen(PORT,()=>console.log(`AstroQuiz authority listening on ${PORT}`));